"""
Digest generator.
Builds formatted markdown digest from evaluated items.
"""

import json
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from src.services.db import get_connection
from src.services.config import (
    GENAI_NEWS_MIN_RELEVANCE,
    PRODUCT_IDEAS_MIN_RELEVANCE,
    MAX_ITEMS_IN_DIGEST,
)
from src.tools.prefilter import Persona

logger = logging.getLogger(__name__)

# Output directory (project root)
OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent


@dataclass
class DigestItem:
    """A single item in the digest."""
    title: str
    url: str
    source: str
    relevance_score: float
    topic: str
    why_it_matters: str
    published_at: str


@dataclass
class DigestResult:
    """Result of digest generation."""
    persona: str
    item_count: int
    file_path: str


def get_evaluated_items(persona: Persona, min_score: float, limit: int) -> list[DigestItem]:
    """Fetch evaluated items from database above the minimum score."""
    conn = get_connection()
    try:
        cursor = conn.cursor()
        
        cursor.execute("""
            SELECT 
                i.title,
                i.url,
                i.source,
                i.published_at,
                e.relevance_score,
                e.evaluation_json
            FROM evaluations e
            JOIN ingested_items i ON e.item_id = i.id
            WHERE e.persona = ?
              AND e.relevance_score >= ?
            ORDER BY e.relevance_score DESC
            LIMIT ?
        """, (persona.value, min_score, limit))
        
        items = []
        for row in cursor.fetchall():
            # Parse evaluation JSON
            eval_data = {}
            try:
                eval_data = json.loads(row["evaluation_json"]) if row["evaluation_json"] else {}
            except json.JSONDecodeError:
                pass
            
            items.append(DigestItem(
                title=row["title"],
                url=row["url"],
                source=row["source"],
                relevance_score=row["relevance_score"],
                topic=eval_data.get("topic", "General"),
                why_it_matters=eval_data.get("why_it_matters", ""),
                published_at=row["published_at"]
            ))
        
        return items
        
    finally:
        conn.close()


def format_digest_markdown(items: list[DigestItem], persona: Persona) -> str:
    """Format items into a markdown digest."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    
    # Header
    if persona == Persona.GENAI_NEWS:
        title = "🤖 AI & Tech Digest"
        subtitle = "Today's top AI/ML news curated by your local AI"
    else:
        title = "💡 Product Ideas Digest"
        subtitle = "Interesting products and startup ideas"
    
    lines = [
        f"# {title}",
        f"**Date:** {today}",
        f"**Items:** {len(items)}",
        "",
        f"*{subtitle}*",
        "",
        "---",
        "",
    ]
    
    if not items:
        lines.append("*No items matched the criteria today.*")
        return "\n".join(lines)
    
    # Items
    for i, item in enumerate(items, 1):
        score_bar = "█" * int(item.relevance_score * 10) + "░" * (10 - int(item.relevance_score * 10))
        
        lines.extend([
            f"## {i}. {item.title}",
            "",
            f"**Score:** {score_bar} {item.relevance_score:.1f}",
            f"**Source:** {item.source} | **Topic:** {item.topic}",
            "",
        ])
        
        if item.why_it_matters:
            lines.extend([
                f"**Why it matters:** {item.why_it_matters}",
                "",
            ])
        
        lines.extend([
            f"🔗 [Read more]({item.url})",
            "",
            "---",
            "",
        ])
    
    # Footer
    lines.extend([
        "",
        f"*Generated by AI Digest System at {datetime.now(timezone.utc).strftime('%H:%M UTC')}*",
    ])
    
    return "\n".join(lines)


def generate_digest(persona: Persona) -> DigestResult:
    """Generate a digest for the given persona."""
    
    # Get min score based on persona
    if persona == Persona.GENAI_NEWS:
        min_score = GENAI_NEWS_MIN_RELEVANCE
    else:
        min_score = PRODUCT_IDEAS_MIN_RELEVANCE
    
    print(f"\n{'='*60}")
    print(f"  Generating Digest: {persona.value.upper()}")
    print(f"{'='*60}")
    
    # Step 1: Get evaluated items
    print(f"\n📊 Fetching items (score >= {min_score})...")
    items = get_evaluated_items(persona, min_score, MAX_ITEMS_IN_DIGEST)
    print(f"   Found: {len(items)} items")
    
    if items:
        print("\n📰 Top items:")
        for i, item in enumerate(items[:5], 1):
            print(f"   {i}. [{item.relevance_score:.1f}] {item.title[:50]}...")
    
    # Step 2: Format as markdown
    print("\n📝 Formatting digest...")
    markdown = format_digest_markdown(items, persona)
    
    # Step 3: Save to file
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"digest_{persona.value}_{today}.md"
    file_path = OUTPUT_DIR / filename
    
    print(f"\n💾 Saving to: {file_path}")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(markdown)
    
    print(f"   ✅ Saved!")
    
    return DigestResult(
        persona=persona.value,
        item_count=len(items),
        file_path=str(file_path)
    )


def generate_all_digests() -> list[DigestResult]:
    """Generate digests for all enabled personas."""
    from src.services.config import PERSONA_GENAI_NEWS_ENABLED, PERSONA_PRODUCT_IDEAS_ENABLED
    
    results = []
    
    if PERSONA_GENAI_NEWS_ENABLED:
        result = generate_digest(Persona.GENAI_NEWS)
        results.append(result)
    
    if PERSONA_PRODUCT_IDEAS_ENABLED:
        result = generate_digest(Persona.PRODUCT_IDEAS)
        results.append(result)
    
    return results


# ---------------------------------------------------------------------------
# Quick Test
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    print("=" * 60)
    print("  Testing Digest Generator")
    print("=" * 60)
    
    # Generate GENAI_NEWS digest
    result = generate_digest(Persona.GENAI_NEWS)
    
    print(f"\n{'='*60}")
    print("  Digest Generated!")
    print(f"{'='*60}")
    print(f"   Persona: {result.persona}")
    print(f"   Items:   {result.item_count}")
    print(f"   File:    {result.file_path}")
    
    # Show preview
    print(f"\n📄 Preview (first 500 chars):")
    print("-" * 40)
    with open(result.file_path, "r", encoding="utf-8") as f:
        preview = f.read()[:500]
        print(preview)
    print("-" * 40)
    
    print("\n✅ Done!")